version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: exchange_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_password
    ports:
      - "5432:5432"
    networks:
      - exchange_network

networks:
  exchange_network:
    driver: bridge 